import fs from 'node:fs'
import path from 'node:path'
import { buildSiteImagesMapping, extractFromHtml, type SiteListing } from './katalystListingCards.ts'

function main() {
  const repoRoot = process.cwd()
  const workspaceRoot = path.resolve(repoRoot, '..')

  const inputs = [
    path.join(workspaceRoot, 'current_lystings.html'),
    path.join(workspaceRoot, 'sold_lystings.html'),
  ].filter((p) => fs.existsSync(p))

  if (!inputs.length) {
    console.error('No site HTML files found. Expected ../current_lystings.html')
    process.exit(1)
  }

  const all: SiteListing[] = []
  for (const p of inputs) {
    const html = fs.readFileSync(p, 'utf8')
    all.push(...extractFromHtml(html))
  }

  const mapping = buildSiteImagesMapping(all)
  const outPath = path.join(repoRoot, 'src', 'data', 'generated', 'siteImages.ts')
  const file = `/* eslint-disable */
// Auto-generated by \`npm run extract:site-images\` from current_lystings.html + sold_lystings.html (download fresh pages first).
export const siteImages = ${JSON.stringify(mapping, null, 2)} as const;
`
  fs.mkdirSync(path.dirname(outPath), { recursive: true })
  fs.writeFileSync(outPath, file, 'utf8')
  console.log(`Wrote ${outPath} with ${Object.keys(mapping.byNormalizedAddress).length} addresses`)
}

main()
