import fs from 'node:fs'
import path from 'node:path'
import { extractFromHtml, buildSiteImagesMapping, type SiteListing } from './katalystListingCards.ts'
function decodeHtmlEntities(s: string) {
  return s
    .replaceAll('&amp;', '&')
    .replaceAll('&nbsp;', ' ')
    .replaceAll('&#8217;', "'")
}

/** Pull PDF / Office file links from a property page HTML. */
export function extractDocumentLinks(html: string): Array<{ name: string; url: string }> {
  const out: Array<{ name: string; url: string }> = []
  const seen = new Set<string>()
  const re = /<a[^>]+href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/gi
  let m: RegExpExecArray | null
  while ((m = re.exec(html)) !== null) {
    const href = m[1] ?? ''
    if (!/\.(pdf|docx?|xlsx?)(\?|#|$)/i.test(href)) continue
    let url = href
    if (!href.startsWith('http')) {
      url = href.startsWith('/') ? `https://katalystteam.com${href}` : `https://katalystteam.com/${href}`
    }
    if (seen.has(url)) continue
    seen.add(url)
    const inner = decodeHtmlEntities((m[2] ?? '').replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim())
    const fallback = decodeURIComponent(url.split('/').pop()?.split('?')[0] ?? 'Document')
    out.push({ name: inner || fallback, url })
  }
  return out
}

function listingUrlIsFetchable(url: string): boolean {
  try {
    const u = new URL(url)
    return u.hostname.includes('katalystteam.com') && u.pathname !== '/' && u.pathname.length > 1
  } catch {
    return false
  }
}

async function fetchHtml(url: string): Promise<string | null> {
  const res = await fetch(url, {
    headers: { 'User-Agent': 'Mozilla/5.0 (compatible; KatalystDashboardDocSync/1.0)' },
    redirect: 'follow',
  })
  if (!res.ok) {
    console.warn(`  HTTP ${res.status} for ${url}`)
    return null
  }
  return res.text()
}

async function main() {
  const repoRoot = process.cwd()
  const workspaceRoot = path.resolve(repoRoot, '..')

  const inputs = [
    path.join(workspaceRoot, 'current_lystings.html'),
    path.join(workspaceRoot, 'sold_lystings.html'),
  ].filter((p) => fs.existsSync(p))

  if (!inputs.length) {
    console.error('No site HTML files found. Expected ../current_lystings.html — run npm run fetch:katalyst-html first.')
    process.exit(1)
  }

  const all: SiteListing[] = []
  for (const p of inputs) {
    const html = fs.readFileSync(p, 'utf8')
    all.push(...extractFromHtml(html))
  }

  const { byNormalizedAddress } = buildSiteImagesMapping(all)
  type DocRow = { name: string; url: string }
  const docsByAddress: Record<string, DocRow[]> = {}

  const entries = Object.entries(byNormalizedAddress)
  console.log(`Fetching ${entries.length} property pages for document links…`)

  for (const [addrKey, row] of entries) {
    if (!listingUrlIsFetchable(row.listingUrl)) {
      console.warn(`  Skip (no detail URL): ${row.addressText}`)
      continue
    }
    process.stdout.write(`  ${row.addressText.slice(0, 52)}… `)
    const html = await fetchHtml(row.listingUrl)
    if (!html) {
      console.log('fail')
      continue
    }
    const docs = extractDocumentLinks(html)
    docsByAddress[addrKey] = docs
    console.log(docs.length ? `${docs.length} file(s)` : 'no files')
    await new Promise((r) => setTimeout(r, 400))
  }

  const outPath = path.join(repoRoot, 'src', 'data', 'generated', 'katalystDocuments.ts')
  const file = `/* eslint-disable */
// Auto-generated by \`npm run extract:katalyst-documents\`. Requires network; uses listing URLs from Current/Sold LYSTings HTML.
export const katalystDocuments = ${JSON.stringify({ byNormalizedAddress: docsByAddress }, null, 2)} as const;
`
  fs.mkdirSync(path.dirname(outPath), { recursive: true })
  fs.writeFileSync(outPath, file, 'utf8')
  console.log(`Wrote ${outPath}`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
