import fs from 'node:fs'
import path from 'node:path'
import { dashboardData } from '../src/data/generated/dashboardData.ts'
import { gdriveAddressKey, matchGdriveFolder, type GdriveFolder } from '../src/lib/gdriveFolderMatch.ts'

const ROOT_FOLDER_ID = '1LMtw2fnyYvY8NWKxrZVSDVRzhgO-dvDc'

async function fetchGdriveFolders(): Promise<GdriveFolder[]> {
  const res = await fetch(`https://drive.google.com/embeddedfolderview?id=${ROOT_FOLDER_ID}#list`, {
    headers: { 'User-Agent': 'Mozilla/5.0 (compatible; KatalystDashboardGDriveSync/1.0)' },
  })
  if (!res.ok) throw new Error(`Drive folder fetch failed: HTTP ${res.status}`)
  const html = await res.text()
  const folders: GdriveFolder[] = []
  const re =
    /id="entry-([^"]+)"[\s\S]*?href="(https:\/\/drive\.google\.com\/drive\/folders\/[^"]+)"[\s\S]*?flip-entry-title">([^<]+)</g
  let m: RegExpExecArray | null
  while ((m = re.exec(html)) !== null) {
    folders.push({
      id: m[1]!,
      url: m[2]!,
      title: m[3]!.replace(/&#39;/g, "'").trim(),
    })
  }
  return folders
}

async function main() {
  console.log('Fetching Google Drive folders…')
  const folders = await fetchGdriveFolders()
  console.log(`Found ${folders.length} folders`)

  const byNormalizedAddress: Record<string, string> = {}
  const unmatched: string[] = []

  for (const listing of dashboardData.listings) {
    const key = gdriveAddressKey(listing.address)
    if (byNormalizedAddress[key]) continue

    const match = matchGdriveFolder(listing.address, folders)
    if (match) {
      byNormalizedAddress[key] = match.url
      console.log(`  matched: ${listing.address} -> ${match.title}`)
    } else {
      unmatched.push(listing.address)
    }
  }

  const outPath = path.join(process.cwd(), 'src', 'data', 'generated', 'gdriveDocuments.ts')
  const file = `/* eslint-disable */
// Auto-generated by \`npm run extract:gdrive-documents\`. Maps listing addresses to Google Drive folders.
export const gdriveDocuments = ${JSON.stringify({ rootFolderId: ROOT_FOLDER_ID, byNormalizedAddress }, null, 2)} as const;
`
  fs.mkdirSync(path.dirname(outPath), { recursive: true })
  fs.writeFileSync(outPath, file, 'utf8')
  console.log(`Wrote ${outPath} (${Object.keys(byNormalizedAddress).length} matches, ${unmatched.length} unmatched)`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
