/**
 * Local webhook receiver for GHL Email Events (Opened / Clicked).
 *
 * Why: GHL public APIs we can access provide aggregate stats, but not a recipient-level list.
 * This listener + a GHL workflow webhook gives us per-contact events to rank top contacts.
 *
 * Run:
 *   npm run dev:webhooks
 *
 * Expected JSON payload (configure in GHL workflow webhook action):
 *   {
 *     "event": "opened" | "clicked",
 *     "listingId": "86agdcyuv",           // recommended: hardcode per-property workflow
 *     "contact": { "id": "...", "name": "...", "email": "...", "phone": "..." },
 *     "bulkRequestId": "...",             // optional
 *     "campaignId": "...",                // optional
 *     "occurredAt": "2026-05-26T..."      // optional
 *   }
 *
 * Output (local-only; ignored by git):
 *   src/data/generated/ghlContactEngagement.private.ts
 */
import fs from 'node:fs'
import http from 'node:http'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { ghlCampaignEngagementByListingId } from '../src/data/generated/ghlCampaignEngagement'

type IncomingPayload = {
  event?: unknown
  listingId?: unknown
  bulkRequestId?: unknown
  campaignId?: unknown
  occurredAt?: unknown
  contact?: unknown
}

type ContactPayload = {
  id?: unknown
  name?: unknown
  email?: unknown
  phone?: unknown
}

type ContactAgg = {
  id: string
  name: string
  email?: string
  phone?: string
  opened: number
  clicked: number
  score: number
}

function safeString(x: unknown): string | null {
  if (typeof x !== 'string') return null
  const s = x.trim()
  return s ? s : null
}

function json(res: http.ServerResponse, status: number, body: unknown) {
  res.statusCode = status
  res.setHeader('content-type', 'application/json; charset=utf-8')
  res.end(JSON.stringify(body))
}

function readJson(req: http.IncomingMessage): Promise<unknown> {
  return new Promise((resolve, reject) => {
    let data = ''
    req.on('data', (c) => {
      data += String(c)
      if (data.length > 2_000_000) reject(new Error('payload too large'))
    })
    req.on('end', () => {
      try {
        resolve(data ? JSON.parse(data) : {})
      } catch (e) {
        reject(e)
      }
    })
    req.on('error', reject)
  })
}

function score(opened: number, clicked: number): number {
  return Math.max(0, Math.round(opened + clicked * 2))
}

function findListingIdFromCampaignIds(bulkRequestId: string | null, campaignId: string | null): string | null {
  for (const [listingId, entry] of Object.entries(ghlCampaignEngagementByListingId)) {
    for (const c of entry.campaigns ?? []) {
      if (bulkRequestId && c.bulkRequestId === bulkRequestId) return listingId
      if (campaignId && c.campaignId === campaignId) return listingId
    }
  }
  return null
}

function outPath(): string {
  const __filename = fileURLToPath(import.meta.url)
  const __dirname = path.dirname(__filename)
  return path.join(__dirname, '..', 'src', 'data', 'generated', 'ghlContactEngagement.private.ts')
}

function loadExisting(): Record<string, { contacts: ContactAgg[] }> {
  const p = outPath()
  if (!fs.existsSync(p)) return {}
  try {
    // We don't import/execute; we parse the JSON-like array from the file content.
    const text = fs.readFileSync(p, 'utf8')
    const m = text.match(/export const ghlContactEngagementByListingId:[^=]*=\\s*(\\{[\\s\\S]*\\})\\s*$/m)
    if (!m) return {}
    // eslint-disable-next-line no-new-func
    const obj = Function(`\"use strict\"; return (${m[1]});`)() as Record<string, { contacts: ContactAgg[] }>
    return obj && typeof obj === 'object' ? obj : {}
  } catch {
    return {}
  }
}

function writeFile(map: Record<string, { contacts: ContactAgg[] }>) {
  const p = outPath()
  fs.mkdirSync(path.dirname(p), { recursive: true })
  fs.writeFileSync(
    p,
    [
      '/** Generated by scripts/ghl-webhook-listener.ts — LOCAL ONLY (contains contact PII). */',
      'export const ghlContactEngagementByListingId: Record<string, { contacts: Array<{',
      '  id: string',
      '  name: string',
      '  email?: string',
      '  phone?: string',
      '  opened: number',
      '  clicked: number',
      '  score: number',
      '}> }> = ' + JSON.stringify(map, null, 2) + ';',
      '',
    ].join('\n'),
    'utf8',
  )
}

function upsertEvent(map: Record<string, { contacts: ContactAgg[] }>, listingId: string, ev: 'opened' | 'clicked', c: ContactAgg) {
  const entry = (map[listingId] ??= { contacts: [] })
  const idx = entry.contacts.findIndex((x) => x.id === c.id)
  const cur = idx >= 0 ? entry.contacts[idx] : null
  const next: ContactAgg =
    cur == null
      ? { ...c, opened: ev === 'opened' ? 1 : 0, clicked: ev === 'clicked' ? 1 : 0, score: 0 }
      : {
          ...cur,
          name: cur.name || c.name,
          email: cur.email ?? c.email,
          phone: cur.phone ?? c.phone,
          opened: cur.opened + (ev === 'opened' ? 1 : 0),
          clicked: cur.clicked + (ev === 'clicked' ? 1 : 0),
          score: 0,
        }

  next.score = score(next.opened, next.clicked)
  if (idx >= 0) entry.contacts[idx] = next
  else entry.contacts.push(next)

  entry.contacts.sort((a, b) => b.score - a.score)
}

const port = Number(process.env.GHL_WEBHOOK_PORT ?? 8787)

const server = http.createServer(async (req, res) => {
  const url = new URL(req.url ?? '/', `http://${req.headers.host ?? 'localhost'}`)

  if (req.method === 'GET' && url.pathname === '/health') {
    return json(res, 200, { ok: true })
  }

  if (req.method === 'POST' && url.pathname === '/ghl/email-event') {
    try {
      const body = (await readJson(req)) as IncomingPayload
      const evRaw = safeString(body.event)?.toLowerCase()
      const ev = evRaw === 'opened' || evRaw === 'clicked' ? evRaw : null
      if (!ev) return json(res, 400, { ok: false, error: 'Missing/invalid `event` (opened|clicked)' })

      const contact = (body.contact ?? {}) as ContactPayload
      const id = safeString(contact.id) ?? safeString(contact.email) ?? safeString(contact.phone)
      if (!id) return json(res, 400, { ok: false, error: 'Missing contact.id (or email/phone)' })

      const name = safeString(contact.name) ?? 'Unknown contact'
      const email = safeString(contact.email) ?? undefined
      const phone = safeString(contact.phone) ?? undefined

      const explicitListingId = safeString(body.listingId)
      const bulkRequestId = safeString(body.bulkRequestId)
      const campaignId = safeString(body.campaignId)
      const listingId = explicitListingId ?? findListingIdFromCampaignIds(bulkRequestId, campaignId)
      if (!listingId) {
        return json(res, 400, {
          ok: false,
          error: 'Missing listingId and could not infer from campaignId/bulkRequestId',
        })
      }

      const map = loadExisting()
      upsertEvent(map, listingId, ev, { id, name, email, phone, opened: 0, clicked: 0, score: 0 })
      writeFile(map)

      return json(res, 200, { ok: true, listingId })
    } catch (e) {
      return json(res, 500, { ok: false, error: String(e) })
    }
  }

  return json(res, 404, { ok: false, error: 'Not found' })
})

server.listen(port, () => {
  // eslint-disable-next-line no-console
  console.log(`GHL webhook listener on http://localhost:${port}`)
  // eslint-disable-next-line no-console
  console.log(`POST events to http://localhost:${port}/ghl/email-event`)
})

