/**
 * Imports a GHL “Email Statistics Details” CSV export and writes a local-only
 * contact leaderboard file for a single listing.
 *
 * This file contains contact PII and is ignored by git:
 *   src/data/generated/ghlContactEngagement.private.ts
 *
 * Usage:
 *   npm run import:ghl-email-stats -- --listingId 86agdcyuv --csv ../GHL/boston-email-stats.csv
 *
 * Scoring:
 *   score = opened + clicked * 2
 */
import fs from 'node:fs'
import path from 'node:path'
import Papa from 'papaparse'

type Row = Record<string, unknown>

function argValue(flag: string): string | null {
  const idx = process.argv.indexOf(flag)
  if (idx === -1) return null
  const v = process.argv[idx + 1]
  return typeof v === 'string' && v.trim() ? v.trim() : null
}

function normHeader(s: string): string {
  return s.toLowerCase().replace(/\s+/g, ' ').trim()
}

function pickField(row: Row, includes: RegExp[]): string | null {
  for (const [k, v] of Object.entries(row)) {
    const hk = normHeader(k)
    if (!includes.some((re) => re.test(hk))) continue
    if (v == null) continue
    const s = String(v).trim()
    if (s) return s
  }
  return null
}

function pickNumber(row: Row, includes: RegExp[]): number {
  const raw = pickField(row, includes)
  if (!raw) return 0
  const n = Number(String(raw).replace(/[^\d.-]/g, ''))
  return Number.isFinite(n) ? n : 0
}

function stableId(name: string, email: string | null, phone: string | null): string {
  const base = (email ?? phone ?? name).toLowerCase().trim()
  // simple non-crypto hash; stable enough for UI keys
  let h = 2166136261
  for (let i = 0; i < base.length; i++) {
    h ^= base.charCodeAt(i)
    h = Math.imul(h, 16777619)
  }
  return `c_${(h >>> 0).toString(16)}`
}

function score(opened: number, clicked: number): number {
  return Math.max(0, Math.round(opened + clicked * 2))
}

function main() {
  const listingId = argValue('--listingId')
  const csvPath = argValue('--csv')
  if (!listingId || !csvPath) {
    console.error('Usage: --listingId <id> --csv <path-to-export.csv>')
    process.exit(1)
  }

  const absCsv = path.isAbsolute(csvPath) ? csvPath : path.join(process.cwd(), csvPath)
  if (!fs.existsSync(absCsv)) {
    console.error(`CSV not found: ${absCsv}`)
    if (csvPath.includes('/absolute/path/to/')) {
      console.error('')
      console.error('Replace the placeholder path with your real GHL export file, e.g.:')
      console.error('  npm run import:ghl-email-stats -- --listingId 86agdcyuv --csv ../GHL/boston-email-stats.csv')
      console.error('')
      console.error('Export from GHL: Email campaign → Email Statistics Details → Export CSV')
    }
    process.exit(1)
  }
  const csv = fs.readFileSync(absCsv, 'utf8')

  const parsed = Papa.parse<Row>(csv, { header: true, skipEmptyLines: true })
  if (parsed.errors?.length) {
    console.error(parsed.errors[0])
    process.exit(1)
  }

  const map = new Map<string, { id: string; name: string; email?: string; phone?: string; opened: number; clicked: number }>()

  for (const row of parsed.data) {
    if (!row || typeof row !== 'object') continue

    const name =
      pickField(row, [/contact name/, /^name$/]) ??
      pickField(row, [/first name/, /last name/]) ??
      'Unknown'

    const email = pickField(row, [/email/])
    const phone = pickField(row, [/phone/, /mobile/])

    const opened = pickNumber(row, [/open/])
    const clicked = pickNumber(row, [/click/])

    const id = stableId(name, email, phone)
    const prev = map.get(id)
    if (!prev) {
      map.set(id, { id, name, email: email ?? undefined, phone: phone ?? undefined, opened, clicked })
    } else {
      prev.opened += opened
      prev.clicked += clicked
      prev.email = prev.email ?? (email ?? undefined)
      prev.phone = prev.phone ?? (phone ?? undefined)
      if (prev.name === 'Unknown' && name !== 'Unknown') prev.name = name
    }
  }

  const contacts = [...map.values()]
    .map((c) => ({ ...c, score: score(c.opened, c.clicked) }))
    .sort((a, b) => b.score - a.score)

  const outPath = path.join(process.cwd(), 'src', 'data', 'generated', 'ghlContactEngagement.private.ts')
  fs.mkdirSync(path.dirname(outPath), { recursive: true })
  fs.writeFileSync(
    outPath,
    [
      '/** Generated by scripts/import-ghl-email-stats.ts — LOCAL ONLY (contains contact PII). */',
      'export const ghlContactEngagementByListingId: Record<string, { contacts: Array<{',
      '  id: string',
      '  name: string',
      '  email?: string',
      '  phone?: string',
      '  opened: number',
      '  clicked: number',
      '  score: number',
      '}> }> = {',
      `  ${JSON.stringify(listingId)}: {`,
      `    contacts: ${JSON.stringify(contacts, null, 4).replace(/\n/g, '\n    ')},`,
      '  },',
      '}',
      '',
    ].join('\n'),
    'utf8',
  )

  console.log(`Wrote ${outPath}`)
  console.log(`Contacts: ${contacts.length}`)
  console.log(`Top: ${contacts.slice(0, 3).map((c) => `${c.name} (${c.score})`).join(', ')}`)
}

main()

