/**
 * Pulls all contacts for GHL_LOCATION_ID and counts tags shaped `prop:<listingTaskId>`
 * (e.g. prop:86ae6xey6). Writes scores to src/data/generated/ghlEngagement.ts
 *
 * Setup:
 *   cp .env.example .env.local   # add GHL_API_TOKEN + GHL_LOCATION_ID (never commit)
 *   npm run sync:ghl-engagement
 *
 * Tag contacts in GHL with prop:<same id as listing.id in dashboardData> to attribute
 * engagement to that property. Tune scoreFormula() as needed.
 */
import fs from 'node:fs'
import path from 'node:path'
import { config } from 'dotenv'

config({ path: path.join(process.cwd(), '.env.local') })
config({ path: path.join(process.cwd(), '..', '.env.local') })

const GHL_BASE_URL = process.env.GHL_BASE_URL ?? 'https://services.leadconnectorhq.com'
const GHL_API_VERSION = '2021-07-28'
const PROP_TAG_PREFIX = 'prop:'

function headers(): HeadersInit {
  const token = process.env.GHL_API_TOKEN ?? ''
  return {
    Authorization: `Bearer ${token}`,
    'Content-Type': 'application/json',
    Version: GHL_API_VERSION,
  }
}

function contactTags(c: Record<string, unknown>): string[] {
  const raw = c.tags
  if (!Array.isArray(raw)) return []
  return raw
    .map((x) => {
      if (typeof x === 'string') return x
      if (x && typeof x === 'object' && 'name' in x && typeof (x as { name: unknown }).name === 'string')
        return (x as { name: string }).name
      return ''
    })
    .filter(Boolean)
}

function startAfterMs(c: Record<string, unknown>): number | null {
  const da = c.dateAdded
  if (da == null) return null
  if (typeof da === 'number') return da
  if (typeof da === 'string') {
    if (/^\d+$/.test(da)) return Number(da)
    try {
      const s = da.replace('Z', '+00:00')
      return new Date(s).getTime()
    } catch {
      return null
    }
  }
  return null
}

/** Map raw contact count per listing → 0–100 display score (edit to taste). */
function scoreFormula(contactCount: number): number {
  if (contactCount <= 0) return 0
  return Math.min(100, Math.round(8 + contactCount * 9.2))
}

async function fetchAllContacts(locationId: string): Promise<Record<string, unknown>[]> {
  const out: Record<string, unknown>[] = []
  let startAfter: number | null = null
  let startAfterId: string | null = null
  const url = `${GHL_BASE_URL}/contacts/`

  for (;;) {
    const params = new URLSearchParams({ locationId, limit: '100' })
    if (startAfter != null && startAfterId) {
      params.set('startAfter', String(startAfter))
      params.set('startAfterId', startAfterId)
    }
    const res = await fetch(`${url}?${params}`, { headers: headers() })
    if (!res.ok) {
      const text = await res.text()
      throw new Error(`GHL ${res.status}: ${text.slice(0, 400)}`)
    }
    const data = (await res.json()) as { contacts?: Record<string, unknown>[] }
    const batch = data.contacts ?? []
    if (batch.length === 0) break
    out.push(...batch)
    const last = batch[batch.length - 1]
    startAfterId = String(last.id ?? '')
    startAfter = startAfterMs(last)
    if (!startAfterId || startAfter == null) break
  }
  return out
}

function aggregateListingCounts(contacts: Record<string, unknown>[]): Map<string, number> {
  const counts = new Map<string, number>()
  for (const c of contacts) {
    for (const tag of contactTags(c)) {
      const t = tag.trim()
      if (!t.toLowerCase().startsWith(PROP_TAG_PREFIX)) continue
      const id = t.slice(PROP_TAG_PREFIX.length).trim()
      if (!id) continue
      counts.set(id, (counts.get(id) ?? 0) + 1)
    }
  }
  return counts
}

function main() {
  const token = process.env.GHL_API_TOKEN
  const locationId = process.env.GHL_LOCATION_ID
  if (!token || !locationId) {
    console.error('Missing GHL_API_TOKEN or GHL_LOCATION_ID. Copy .env.example → .env.local and fill values.')
    process.exit(1)
  }

  fetchAllContacts(locationId)
    .then((contacts) => {
      const counts = aggregateListingCounts(contacts)
      const lines: string[] = ['/** Generated by scripts/sync-ghl-engagement.ts — do not edit by hand. */']
      lines.push('export const ghlEngagementByListingId: Record<string, { ghlScore: number }> = {')
      const ids = [...counts.keys()].sort()
      for (const id of ids) {
        const n = counts.get(id) ?? 0
        const score = scoreFormula(n)
        lines.push(`  ${JSON.stringify(id)}: { ghlScore: ${score} }, // ${n} tagged contact(s)`)
      }
      lines.push('}')
      lines.push('')

      const outPath = path.join(process.cwd(), 'src', 'data', 'generated', 'ghlEngagement.ts')
      fs.mkdirSync(path.dirname(outPath), { recursive: true })
      fs.writeFileSync(outPath, lines.join('\n'), 'utf8')
      console.log(`Wrote ${outPath}`)
      console.log(`Listings with prop:* tags: ${ids.length} (from ${contacts.length} contacts)`)
    })
    .catch((e) => {
      console.error(e)
      process.exit(1)
    })
}

main()
